### ISSUE TITLE
Cannot verify code with Arduino Web Editor

### ISSUE THREAD

**Issue by fengrun85** [Seeed-Studio/Seeed_PM2_5_sensor_HM3301#11]
When I try to verify the code in Arduino Web Editor, this error occurs.

> /home/builder/opt/libraries/latest/grove_laser_pm2_5_sensor_hm3301_1_0_2/Seeed_HM330X.h:76:58: error: 'u32' has not been declared
> 
> HM330XErrorCode IIC_read_bytes(u8 start_reg,u8 *data,u32 data_len);
> 
> ^~~
> 
> /home/builder/opt/libraries/latest/grove_laser_pm2_5_sensor_hm3301_1_0_2/Seeed_HM330X.h:91:48: error: 'u32' has not been declared
> 
> HM330XErrorCode read_sensor_value(u8 *data,u32 data_len);
> 
> ^~~

**Comment by freekode** [comment]
This was fixed in previous version.
Probably library not updated in Arduino Registry

**Comment by fengrun85** [comment]
Hi @Pillar1989
Can you make a new release? Maybe version 1.0.3?
The latest version on Arduino Web Editor is 1.0.2 and fails to compile with SAMD MKR.
I know you fixed some bugs. Please make a new release

Thanks
