### ISSUE TITLE
Dyson Air Quality Monitoring Device

### ISSUE THREAD

**Issue by 30382abeltan** [Seeed-Studio/Seeed_PM2_5_sensor_HM3301#20]
Hello,

I need some help, I have very little coding knowledge and am trying to adjust this code I downloaded from the Dyson foundation, this was from their engineering tutorial where they created a PM2.5 sensor and a Gas sensor. Youtube video here: https://www.youtube.com/watch?v=USHUJzfM5K0.

I've followed the entire tutorial with one exception, I am not using the gas sensor and its corresponding LED because my project revolves around Particulate Matter (PM). The PM2.5 sensor is a Seeed Studio laser PM2.5 sensor. I believe the code doesn't allow the LEDs to work individually and only knows how to turn on and read the sensors when BOTH sensors are plugged in.

How do I rectify/change the code so that the LED corresponds to the single PM 2.5 sensor?

The link to the code is attached below. 

Regards,
Abel 
[jdf_aqi.zip](https://github.com/Seeed-Studio/Seeed_PM2_5_sensor_HM3301/files/13533384/jdf_aqi.zip)

**Comment by Lesords** [comment]
Hello,

I'm very sorry to have kept you waiting so long.

Do you still have this problem now?

**Comment by Lesords** [comment]
Hello,

I\'m going to close this issue, feel free to re-open it if you have any other questions.

[Autocommentary]
