### ISSUE TITLE
Raspberry example

### ISSUE THREAD

**Issue by SimonDanisch** [Seeed-Studio/Seeed_PM2_5_sensor_HM3301#9]
Hi, is there also a raspberry example somewhere? I understand that it's not officially supported yet, but from all I can tell, the "Grove Base Hat" has the correct I2C ports for the sensor, and the C++ code doesn't look very complicated ;)
In case there is no example that could get me started, any pointer on what libraries to use on the raspberry instead of `Arduino.h` and `Wire.h`?

Any help would be much appreciated :)

**Comment by freekode** [comment]
you could try [this](https://github.com/me-no-dev/RasPiArduino)
also as HM3301 is communicating on i2c protocol, you could use any python i2c library for Raspberry PI, there are plenty of tutorials [here](https://learn.sparkfun.com/tutorials/raspberry-pi-spi-and-i2c-tutorial/all) and [here](https://www.instructables.com/id/Raspberry-Pi-I2C-Python/)

**Comment by SimonDanisch** [comment]
I was silly, I didn't see that there is a second page to this forum entry, which is basically the first google result:
https://forum.seeedstudio.com/viewtopic.php?t=32195&start=10#p54846
So there seems to be an official raspberry python example:
https://github.com/Seeed-Studio/grove.py/blob/master/grove/grove_PM2_5_HM3301.py
not sure why it isn't shown on the seeed studio grove website...
This script seems to work perfectly:
https://github.com/home-assistant/home-assistant/pull/30505
